### ISSUE TITLE
[BUG] Wrong aligment of children inside Scroll element

### ISSUE THREAD

**Issue by SogoCZE** [nicbarker/clay#39]
A vertical scroll element aligns its children incorrectly along the vertical axis. In this example, align is set to `TOP` but the Scroll Element aligns to the bottom.

![image](https://github.com/user-attachments/assets/dc35ee1d-d4a2-4bfe-ad38-ac5571dc211a)

**Comment by nicbarker** [comment]
Thanks for the report, luckily I caught this one while working on the new multi configs and haven't backported it 🙂
It was due to a bug in how the min / max scroll offset was calculated when the container itself was larger than its contents, fixed here:
https://github.com/nicbarker/clay/commit/c3f2baf40a6fc0596bae8e90734f96cce06bd7d1
Let me know if it works for you!

**Comment by SogoCZE** [comment]
https://github.com/nicbarker/clay/commit/c3f2baf40a6fc0596bae8e90734f96cce06bd7d1 indeed fixed it!
