### ISSUE TITLE
[BUG] Debug Tools do not scroll on macos

### ISSUE THREAD

**Issue by Spooky309** [nicbarker/clay#98]
Testing with both the 'raylib-sidebar-scrolling-container' C example, and the Odin example. In both, scrolling works as expected, but if I hit D and open the debug tools, that seems to ignore scrolling input entirely. I have a feeling it's got something to do with the way Mac scrolling works where you can let go and it keeps scrolling for a bit (like a phone).

tldr: scroll containers worky, debug tools scroll containers no worky

**Comment by nicbarker** [comment]
Oh dear, yes I see. I've reproduced this locally. Thanks for reporting 🙂 Fix incoming.

**Comment by nicbarker** [comment]
In case you're wondering what the issue was - https://github.com/nicbarker/clay/pull/66 <- this PR changed the default behaviour of floating elements to capture pointer events like scroll and mouse hover (desirable, usually). However the debug tools use a funky setup to get the particular visual appearance they have, which means the pointer events were getting captured by something other than the scroll container. Oops!

**Comment by Spooky309** [comment]
Well, that was fast 😄
